import React from 'react';
import {useEffect,useState} from 'react';
import {Plus,Edit,Trash2,X} from 'lucide-react';
import api from '../../services/api';
const empty={name:'',description:'',price:'',category:'Electronics',stock:'',image:'',isActive:true};
export default function Products(){
    const [products,setProducts]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[error,setError]=useState('');
    const load=()=>api.get('/products/admin/all').then(r=>setProducts(r.data));useEffect(()=>{load()},[]);
    const save=async e=>{e.preventDefault();try{
    const payload={...form,price:Number(form.price),stock:Number(form.stock)};
    editing?await api.put(`/products/${editing}`,payload):await api.post('/products',payload);
    setOpen(false);setEditing(null);setForm(empty);load()}catch(err){setError(err.response?.data?.message||'Save failed')}};
    const edit=p=>{setEditing(p._id);setForm({...p,price:String(p.price),stock:String(p.stock)});setOpen(true)};const del=async id=>{if(confirm('Delete this product?')){await api.delete(`/products/${id}`);load()}};return <div className="admin-page"><div className="admin-top"><div><span className="eyebrow">CATALOG</span><h1>Products</h1><p className="muted">Create and maintain your store inventory.</p></div><button className="btn btn-primary" onClick={()=>{setEditing(null);
        setForm(empty);setError('');setOpen(true)}}><Plus/> Add product</button></div><div className="table-card"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th>Actions</th></tr></thead><tbody>{products.map(p=><tr key={p._id}><td><div className="table-product"><img src={p.image} alt=""/><b>{p.name}</b></div></td><td>{p.category}</td><td>Rs. {p.price.toLocaleString()}</td><td>{p.stock}</td><td><span className={`status ${p.isActive?'delivered':'cancelled'}`}>{p.isActive?'Active':'Inactive'}</span></td><td><button className="icon-btn" onClick={()=>edit(p)}><Edit/></button><button className="icon-btn danger" onClick={()=>del(p._id)}><Trash2/></button></td></tr>)}</tbody></table></div>{open&&<div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={()=>setOpen(false)}><X/></button><span className="eyebrow">PRODUCT</span><h2>{editing?'Edit':'Add'} product</h2>{error&&<div className="alert error">{error}</div>}<form onSubmit={save}><div className="form-grid"><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Category<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Price<input type="number" min="0" required value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Stock<input type="number" min="0" required value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label><label className="wide">Image URL<input value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/></label><label className="wide">Description<textarea required rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><button className="btn btn-primary full">Save product</button></form></div></div>}</div>}
