import express from 'express';
import { createOrder, getAllOrders, getMyOrders, getOrder, updateOrderStatus } from '../controllers/orderController.js';
import { adminOnly, protect } from '../middleware/authMiddleware.js';
const router = express.Router();
router.post('/', protect, createOrder);
router.get('/my', protect, getMyOrders);
router.get('/admin/all', protect, adminOnly, getAllOrders);
router.get('/:id', protect, getOrder);
router.put('/:id/status', protect, adminOnly, updateOrderStatus);
export default router;
