import express from 'express';
import { createProduct, deleteProduct, getAllProducts, getProduct, getProducts, updateProduct } from '../controllers/productController.js';
import { adminOnly, protect } from '../middleware/authMiddleware.js';
const router = express.Router();
router.get('/', getProducts);
router.get('/admin/all', protect, adminOnly, getAllProducts);
router.get('/:id', getProduct);
router.post('/', protect, adminOnly, createProduct);
router.put('/:id', protect, adminOnly, updateProduct);
router.delete('/:id', protect, adminOnly, deleteProduct);
export default router;
